//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Class1
{
	public virtual object Attribute1
	{
		get;
		set;
	}

	public virtual void Operation1()
	{
		throw new System.NotImplementedException();
	}

}

